# Generated by Django 5.0.6 on 2026-03-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_software_softwareimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
