# Generated by Django 5.0.6 on 2026-03-11 00:03

import django.db.models.deletion
from django.db import migrations, models


def seed_lookup_tables(apps, schema_editor):
    AdvisoryService = apps.get_model("website", "AdvisoryService")
    AdvisoryServiceType = apps.get_model("website", "AdvisoryServiceType")
    AdvisoryPriceTerm = apps.get_model("website", "AdvisoryPriceTerm")

    service_type_map = {
        "management": ("management", "Удирдлагын зөвлөх", 1),
        "finance": ("finance", "Санхүүгийн зөвлөх", 2),
        "marketing": ("marketing", "Маркетингийн зөвлөх", 3),
        "hr": ("hr", "Хүний нөөцийн зөвлөх", 4),
        "operations": ("operations", "Үйл ажиллагааны зөвлөх", 5),
        "digital": ("digital", "Дижитал шилжилтийн зөвлөх", 6),
    }
    price_term_map = {
        "fixed": ("fixed", "Төслөөр", 1),
        "monthly": ("monthly", "Сараар", 2),
        "hourly": ("hourly", "Цагаар", 3),
        "custom": ("custom", "Тохиролцоно", 4),
    }

    for key, name, sort_order in service_type_map.values():
        AdvisoryServiceType.objects.get_or_create(key=key, defaults={"name": name, "sort_order": sort_order})
    for key, name, sort_order in price_term_map.values():
        AdvisoryPriceTerm.objects.get_or_create(key=key, defaults={"name": name, "sort_order": sort_order})

    default_service_type = AdvisoryServiceType.objects.get(key="management")
    default_price_term = AdvisoryPriceTerm.objects.get(key="custom")

    for advisory in AdvisoryService.objects.all():
        advisory.service_type_ref = AdvisoryServiceType.objects.filter(key=advisory.service_type).first() or default_service_type
        advisory.price_terms_ref = AdvisoryPriceTerm.objects.filter(key=advisory.price_terms).first() or default_price_term
        advisory.save(update_fields=["service_type_ref", "price_terms_ref"])


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_advisoryservice_structure_update"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryPriceTerm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="AdvisoryServiceType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AddField(
            model_name="advisoryservice",
            name="price_terms_ref",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="website.advisorypriceterm"),
        ),
        migrations.AddField(
            model_name="advisoryservice",
            name="service_type_ref",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="website.advisoryservicetype"),
        ),
        migrations.RunPython(seed_lookup_tables, migrations.RunPython.noop),
        migrations.RemoveField(model_name="advisoryservice", name="price_terms"),
        migrations.RemoveField(model_name="advisoryservice", name="service_type"),
        migrations.RenameField(model_name="advisoryservice", old_name="price_terms_ref", new_name="price_terms"),
        migrations.RenameField(model_name="advisoryservice", old_name="service_type_ref", new_name="service_type"),
        migrations.AlterField(
            model_name="advisoryservice",
            name="price_terms",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="advisory_services", to="website.advisorypriceterm"),
        ),
        migrations.AlterField(
            model_name="advisoryservice",
            name="service_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="advisory_services", to="website.advisoryservicetype"),
        ),
    ]
