# Generated by Django 5.0.6 on 2026-03-11 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_lookup_tables_for_advisory_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("advisory_service", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="website.advisoryservice")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="advisory_likes", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="advisorylike",
            constraint=models.UniqueConstraint(fields=("advisory_service", "user"), name="unique_advisory_like"),
        ),
    ]
