# Generated by Django 5.0.6 on 2026-03-11 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_advisorylike"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="article_images/")),
                ("published_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("article_type", models.ForeignKey(limit_choices_to={"type": "article"}, on_delete=django.db.models.deletion.PROTECT, related_name="articles", to="website.category")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_articles", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="articles", to="website.customer")),
            ],
            options={
                "ordering": ["-published_date", "-id"],
            },
        ),
    ]
