# Generated by Django 6.0.6 on 2026-08-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_footer_menu_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='partner_logos/')),
                ('link_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
    ]
