# Generated by Django 6.0.6 on 2026-08-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_partnerorganization_alter_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_label', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='slides/')),
                ('link_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_date', '-id'],
            },
        ),
    ]
