# Generated by Django 5.0.6 on 2026-02-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_type',
            field=models.CharField(choices=[('org', 'Organization'), ('person', 'Person')], default='org', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], default='bronze', max_length=10),
        ),
    ]
