# Generated by Django 5.0.6 on 2026-02-26 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Software",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("development_start_year", models.PositiveSmallIntegerField()),
                ("description", models.TextField(blank=True)),
                ("introduction", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("price_type", models.CharField(choices=[("rent", "Rent"), ("sale", "Sale")], default="rent", max_length=10)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_softwares", to=settings.AUTH_USER_MODEL)),
                ("developer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="softwares", to="website.customer")),
                ("program_type", models.ForeignKey(limit_choices_to={"type": "program"}, on_delete=django.db.models.deletion.PROTECT, related_name="software_program_types", to="website.category")),
                ("advisory_sectors", models.ManyToManyField(blank=True, limit_choices_to={"type": "advisory"}, related_name="software_advisory_sectors", to="website.category")),
            ],
        ),
        migrations.CreateModel(
            name="SoftwareImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="software_images/")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("software", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="website.software")),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
