# Generated by Django 5.0.6 on 2026-03-11 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_software_is_featured"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("introduction", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="advisory_services", to="website.customer")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_advisory_services", to=settings.AUTH_USER_MODEL)),
                ("service_type", models.ForeignKey(limit_choices_to={"type": "advisory"}, on_delete=django.db.models.deletion.PROTECT, related_name="advisory_services", to="website.category")),
            ],
        ),
        migrations.CreateModel(
            name="AdvisoryServiceImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="advisory_service_images/")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("advisory_service", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="website.advisoryservice")),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
