# Generated by Django 5.0.6 on 2026-03-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_advisoryservice_advisoryserviceimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisoryservice",
            name="service_type",
            field=models.CharField(max_length=255),
        ),
    ]
