# Generated by Django 5.0.6 on 2026-03-11 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_alter_advisoryservice_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisoryservice",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("management", "Удирдлагын зөвлөх"),
                    ("finance", "Санхүүгийн зөвлөх"),
                    ("marketing", "Маркетингийн зөвлөх"),
                    ("hr", "Хүний нөөцийн зөвлөх"),
                    ("operations", "Үйл ажиллагааны зөвлөх"),
                    ("digital", "Дижитал шилжилтийн зөвлөх"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="advisoryservice",
            name="advisory_sectors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type": "advisory"},
                related_name="advisory_service_sectors",
                to="website.category",
            ),
        ),
        migrations.AddField(
            model_name="advisoryservice",
            name="client_organizations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="advisoryservice",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="advisoryservice",
            name="price_terms",
            field=models.CharField(
                choices=[
                    ("fixed", "Төслөөр"),
                    ("monthly", "Сараар"),
                    ("hourly", "Цагаар"),
                    ("custom", "Тохиролцоно"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="advisoryservice",
            name="service_start_year",
            field=models.PositiveSmallIntegerField(default=2024),
        ),
    ]
