# Generated by Django 6.0.6 on 2026-08-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_slide_alter_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(default='Бидний тухай', max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('feature_title', models.CharField(blank=True, max_length=255)),
                ('feature_text', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=120)),
                ('button_url', models.CharField(blank=True, max_length=500)),
                ('circle_right_text', models.CharField(blank=True, max_length=120)),
                ('circle_left_text', models.CharField(blank=True, max_length=120)),
                ('top_image', models.ImageField(blank=True, null=True, upload_to='about_section/')),
                ('bottom_image', models.ImageField(blank=True, null=True, upload_to='about_section/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_date', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('program', 'Program'), ('advisory', 'Advisory'), ('article', 'Article')], max_length=20),
        ),
    ]
