# Generated by Django 5.2.17 on 2026-09-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_aboutsection_alter_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisoryrating',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='softwarerating',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
